name: Tests
on:
  pull_requests:
    types: [opened]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Gradle Test
        run: ./gradlew test

